name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Ejecutar cada domingo a medianoche

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Environment
        run: |
          echo "GitHub Ref: ${{ github.ref }}"
          echo "GitHub Event Name: ${{ github.event_name }}"
          echo "Runner OS: ${{ runner.os }}"
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Debug Python Setup
        run: |
          python --version
          pip --version
          echo "Python location: $(which python)"
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip list
          
      - name: Debug Snyk Token
        run: |
          if [ -n "$SNYK_TOKEN" ]; then
            echo "SNYK_TOKEN is set"
          else
            echo "SNYK_TOKEN is not set"
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Install Snyk
        run: |
          npm install -g snyk
          snyk --version
          
      - name: Check Python dependencies for vulnerabilities with Snyk
        continue-on-error: true  # No fallar el workflow si hay vulnerabilidades
        run: snyk test --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        
      - name: Run Bandit (Python static code analysis)
        continue-on-error: true  # No fallar el workflow si hay vulnerabilidades
        run: |
          pip install bandit
          bandit -r . -x ./tests -o bandit-report.txt -f txt || true
          cat bandit-report.txt
        
      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.txt
          retention-days: 5
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Debug Node.js Setup
        run: |
          node --version
          npm --version
          
      - name: Check JavaScript dependencies with Snyk
        continue-on-error: true  # No fallar el workflow si hay vulnerabilidades
        run: |
          if [ -f package.json ]; then
            snyk test
          else
            echo "No package.json found, skipping JavaScript dependencies check"
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Monitor project for vulnerabilities
        continue-on-error: true  # No fallar el workflow si hay vulnerabilidades
        run: snyk monitor --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - name: Summary
        run: |
          echo "Security scan completed. Check the logs and artifacts for detailed results."
          echo "Remember to review the Bandit report for potential security issues."
